### ISSUE TITLE
Serving static gz files

### ISSUE THREAD

**Issue by saeugetier** [loicortola/nodemcu-espress#5]
Please add a mime for serving gzipped static files. This would help serving a compressed JavaScript library.

**Comment by loicortola** [comment]
Sounds interesting, let me look into that.

**Comment by saeugetier** [comment]
Serving gzipped files ist implemented in the simple webserver https://github.com/marcoskirsch/nodemcu-httpserver

**Comment by loicortola** [comment]
I have finished to implement it. 
Available in 0.4.0
Also, lots of new improvements in this release:
A multi-request buffer, allowing you to really handle concurrent requests well.
