### ISSUE TITLE
use model as a lua module makes unloading difficult

### ISSUE THREAD

**Issue by devyte** [loicortola/nodemcu-espress#6]
The webserver is loaded as a lua module via a require. While this makes the code more elegant, it also makes it necessary to jump through hoops to unload the lua module (consider the accepted answer [here](http://stackoverflow.com/questions/18097333/how-to-drop-all-code-and-memory-space-of-a-lua-module), where the developer of jitlua says there is no reliable way. In larger systems, such as a laptop or game console, it is ok to load modules in that way, but I think it is not very suited to a small embedded application like the ESP.
Examle cases where the module would need to be unloaded in the ESP are, among others:
*if the server were to be disabled
*in case of a mutiprotocol TCP server, which is my usage case

Instead, I suggest switching to a dofile() and returning an object or a function. If no longer needed, the object could just be niled to release and allow gc.

Personally, I prefer to separate the TCP socket server from the http server. This can be done by implementing a dofile() that returns 3 functions: a detector, an installer, and the onReceive callback. Consider the implementation [here](https://github.com/devyte/nodemcu-platform), file tcpserver.lua.

**Comment by loicortola** [comment]
Hi @devyte , thanks for your input.
Indeed, it was more of a code elegance choice.
I like your implementation even though I think your use case is very particular.
I don't think it makes sense for espress to refactor it in such a way.

However, I can add a middleware connector which would expose the relevant methods which you could then use. The closest analogy I can find is when you would provide an express app instance to a regular https server in node.js.

Would that be fine?

**Comment by loicortola** [comment]
Hi @devyte , any feedback on this?

I don't mind using a dofile() instead of the loadfile, My understanding is that the dofile was harder to nil out, but I may be wrong.

**Comment by loicortola** [comment]
After two weeks of non-response, I am considering this issue as solved. Please reopen if interested.
