### ISSUE TITLE
NodeMCU modules requirements

### ISSUE THREAD

**Issue by rodrigoavalente** [loicortola/nodemcu-espress#8]
Hello, first of anything, thanks for the great work, it seems great and I'm planning on use it for a project. However I'm having some issues using some of the samples provided in the repo.

Trying to run the `simple-website-with-forms` sample I'm getting all the values as `nil`, so I would like to know if there is some `node mcu modules` needed as prerequisites to use `nodemcu-espress` properly. Thanks in advance.

**Comment by loicortola** [comment]
Hi @rodrigoavalente , sorry for the super long delay of response (wont happen again ;-) )
yes some node mcu modules are needed, and the latest Dev nodemcu firmware (not the master branch which is getting old).
the following modules are needed:
file, net, node
No other module should be required for the simple-website-with-forms sample.

Let me know when this works so I can close this issue.

**Comment by loicortola** [comment]
After two weeks of non-response, I consider this issue as closed. Please reopen if not solved.
